# Generated by Django 3.1.3 on 2021-04-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20210417_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
