# Generated by Django 3.1.3 on 2021-04-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20210417_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
