# Generated by Django 3.1.3 on 2021-04-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
